// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCA59zufOtjpsPbKjbL6K_8HxrzT3VjbQ',
    appId: '1:359532353621:web:4abab062c121fbaadc1cdc',
    messagingSenderId: '359532353621',
    projectId: 'expense-app-53304',
    authDomain: 'expense-app-53304.firebaseapp.com',
    storageBucket: 'expense-app-53304.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPu8IplPxiXQtl-xlQ8anDoSOnE6EoTM',
    appId: '1:359532353621:android:13f6d6e576aa0567dc1cdc',
    messagingSenderId: '359532353621',
    projectId: 'expense-app-53304',
    storageBucket: 'expense-app-53304.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2APeZy3AmEHQVDCM5ffMWjLBF-ncsUIQ',
    appId: '1:359532353621:ios:46fac49aa6360144dc1cdc',
    messagingSenderId: '359532353621',
    projectId: 'expense-app-53304',
    storageBucket: 'expense-app-53304.appspot.com',
    iosBundleId: 'com.example.expenceTracker',
  );
}
