// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nlH84uzVNckaAks114FIeT5cQ6L-TsQ',
    appId: '1:512428399497:web:0b70cef3a8fa41f320df58',
    messagingSenderId: '512428399497',
    projectId: 'flutter-project-85fb6',
    authDomain: 'flutter-project-85fb6.firebaseapp.com',
    databaseURL: 'https://flutter-project-85fb6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-85fb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDolXad5H-T9ebf4y0UVFJPQtbhL54B70c',
    appId: '1:512428399497:android:bcadf5606faae4ac20df58',
    messagingSenderId: '512428399497',
    projectId: 'flutter-project-85fb6',
    databaseURL: 'https://flutter-project-85fb6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-85fb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1ASVaB-kA7iJGp4XBC5Po5v3Om-JtPbM',
    appId: '1:512428399497:ios:3c9558804e17e0aa20df58',
    messagingSenderId: '512428399497',
    projectId: 'flutter-project-85fb6',
    databaseURL: 'https://flutter-project-85fb6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-85fb6.appspot.com',
    iosBundleId: 'com.example.expenceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1ASVaB-kA7iJGp4XBC5Po5v3Om-JtPbM',
    appId: '1:512428399497:ios:ecff0af6013df73120df58',
    messagingSenderId: '512428399497',
    projectId: 'flutter-project-85fb6',
    databaseURL: 'https://flutter-project-85fb6-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-85fb6.appspot.com',
    iosBundleId: 'com.example.expenceTracker.RunnerTests',
  );
}
